<?php /** @var \Application\UsersProfiles\Row $row */ ?>
<?php $uid = uniqid('form_', false); ?>
<form id="<?=$uid?>" action="<?=$this->url('profile', 'crud')?>" class="form-horizontal" data-ajax method="POST">
    <input type="hidden" name="_method" value="<?=$method?>"/>
    <div class="modal-header">
      <h4 class="modal-title"><?=__('Profile')?></h4>
      <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>
    </div>
    <div class="modal-body">
        <div class="form-group row mb-1">
            <label class="col-form-label col-lg-4" for="first_name"><?=__('First name')?></label>
            <div class="col-lg-8">
                <input class="form-control" id="first_name" name="firstName" value="<?=esc($row->firstName)?>" required />
            </div>
        </div>
        <div class="form-group row mb-1">
            <label class="col-form-label col-lg-4" for="last_name"><?=__('Last name')?></label>
            <div class="col-lg-8">
                <input class="form-control" id="last_name" name="lastName" value="<?=esc($row->lastName)?>" required />
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary"><?=__('Save')?></button>
        <button type="button" class="btn btn-light" data-bs-dismiss="modal"><?= __('Close') ?></button>
    </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>