<?php $uid = uniqid('form_', false); ?>
<div class="card text-center">
  <?php require_once __DIR__ .'/partial/card-header.phtml' ?>
  <div class="card-body">
    <h4 class="card-title"><?= __('Change information') ?></h4>
    <div class="card w-50 center">
      <div class="card-body">
        <form id="<?= $uid ?>" action="<?= $this->url('users', 'change-profile') ?>" class="ajax form-horizontal"
              method="POST">
          <input type="hidden" name="_method" value="<?=$method?>"/>
          <div class="form-group row">
            <label class="col-form-label col-lg-4" for="first_name"><?=__('First name')?></label>
            <div class="col-lg-8">
              <input class="form-control" id="first_name" name="firstName" value="<?=esc($row->firstName)?>" required />
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-lg-4" for="last_name"><?=__('Last name')?></label>
            <div class="col-lg-8">
              <input class="form-control" id="last_name" name="lastName" value="<?=esc($row->lastName)?>" required />
            </div>
          </div>
          <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
        </form>
      </div>
    </div>
  </div>
</div>
